### ISSUE TITLE
Small Feature Suggestion: Customizable Static Time Channels.

### ISSUE THREAD

**Issue by LittleToonCat** [LuigiBlood/sat_wave#10]
Right now, the two time channels (BS-X and Game) will be automatically set to Logical Channel 0000 upon adding one of the two from the list, meaning the emulator will create their own time packet data, based of the player's time settings dynamically (If it's coded to do so).

I do feel like it would leave a bad impression for people who would like to play a Soundlink game within BS-X.  That means if the player downloads such a game 30 minutes past the hour, half of the game will be skipped, and the player would have to wait for another 30 minutes for the clock to reset, having to start, or re-download the game again, so they could play it from the very beginning as intended.

The only way is get around this is by _not_ adding a time channel at all to the channel map, but that means the player would have to wait for 5 to 10 minutes for the game to begin every time.

I think it will be nice if we could customize these time packets ourselves within SatellaWave.  Meaning the user can set the packet to any time they wish, (e.g. 6 minutes past the hour) and the program would instead create a static time packet for the such games to read (using a different Logical Channel), so they can be at the beginning, the middle, or the end of the game every time.

**Comment by LuigiBlood** [comment]
Logical Channel 0000 was not a random thing, it was to make sure every single Soundlink game would work through initialized memory (as such, all 00s).

The point is though, bsnes-plus, and even sd2snes already has a feature for this purpose: You can set up a custom time/date to avoid waiting. It's not a feature in SNES9X for a few reasons such as how I'm not familiar with its GUI code.

Also, not adding a time channel isn't the way to go since a few soundlink games absolutely requires one. I'd just tell the users about the custom time/date feature in bsnes-plus.
